require "haikunator/version"
require "securerandom"

module Haikunator
  class << self
    def haikunate(token_range = 9999, delimiter = "-", excluded_nouns: [], excluded_adjectives: [])
      build(token_range, delimiter, excluded_nouns: excluded_nouns, excluded_adjectives: excluded_adjectives)
    end

    private

    def build(token_range, delimiter, excluded_nouns: [], excluded_adjectives: [])
      filtered_adjectives = excluded_adjectives.present? ? adjectives.filter { |a| !excluded_adjectives.include?(a) } : adjectives
      filtered_nouns = excluded_nouns.present? ? nouns.filter { |n| !excluded_nouns.include?(n) } : nouns
      sections = [
        filtered_adjectives[random_seed % filtered_adjectives.length],
        filtered_nouns[random_seed % filtered_nouns.length],
        token(token_range)
      ]

      sections.compact.join(delimiter)
    end

    def random_seed
      SecureRandom.random_number(4096)
    end

    def token(range)
      SecureRandom.random_number(range) if range > 0
    end

    def adjectives
      %w[
        autumn hidden bitter misty silent empty dry dark summer
        icy delicate quiet cool spring winter patient
        twilight dawn crimson wispy weathered blue billowing
        broken cold damp falling frosty green long late lingering
        bold little morning muddy old red rough still small
        sparkling thrumming shy wandering withered wild mature
        young holy solitary fragrant aged snowy proud floral
        restless divine polished ancient purple lively nameless
        dazzling brave happy enchanting gentle glorious handsome
        marvelous classy calming beautiful amazing urban incredible
        heavenly bright brilliant salty mystic adorable elegant
        astonishing graceful charming gleaming fascinating delightful
        clever captivating fierce fashionable exquisite breathtaking
        exuberant serene majestic radiant melodic harmonious
        captivating jubilant blissful zesty affectionate
        alluring
        ambitious
        appreciative
        authentic
        awesome
        balanced
        benevolent
        blessed
        blithe
        bold
        bountiful
        brave
        brilliant
        buoyant
        caring
        celebrated
        charismatic
        cheerful
        chic
        clever
        compassionate
        confident
        courageous
        creative
        dazzling
        determined
        devoted
        dynamic
        eager
        earnest
        ecstatic
        effervescent
        eloquent
        empathetic
        empowered
        energetic
        engaging
        enthusiastic
        exciting
        exhilarating
        extraordinary
        fabulous
        fantastic
        fearless
        flourishing
        fortunate
        friendly
        fun-loving
        generous
        genuine
        glowing
        gracious
        grateful
        great-hearted
        happy-go-lucky
        harmonious
        heartwarming
        helpful
        heroic
        honorable
        imaginative
        impressive
        incandescent
        inclusive
        independent
        innovative
        inspiring
        intelligent
        joyful
        jovial
        joyous
        kindhearted
        levitating
        lighthearted
        limitless
        loving
        lucky
        luminescent
        luminous
        fantastic
        confident
        lovely
        charming
        fascinating
        amazing
        beautiful
        enthusiastic
        fabulous
        talented
        accomplished
        creative
        passionate
        graceful
        benevolent
        caring
        elegant
        dazzling
        radiant
        splendid
        vivacious
        innovative
        resilient
        extraordinary
        intelligent
        gentle
        optimistic
        warm-hearted
        compassionate
        generous
        inspiring
        cheerful
        vibrant
        precious
        sincere
        harmonious
        valiant
        wise
        witty
        resourceful
        fearless
        diligent
        jovial
        charismatic
        humorous
        adventurous
        diligent
        cultured
        faithful
        peaceful
        insightful
        engaging
        radiant
        lively
        passionate
        dashing
        resilient
        delightful
        majestic
        magnetic
        smooth
        strong
        tender
        motivated
        outstanding
        respectful
        creative
        empowering
        splendid
        abundant
        grateful
        unique
        victorious
        kind
        progressive
        authentic
        understanding
        attentive
        appreciative
        selfless
        vibrant
        enterprising
        fearless
        extraordinary
        productive
        nurturing
        invigorating
        dedicated
        comforting
        empowering
        healthy
        ingenious
        cheerful
        affectionate
        calm
        wise
        indomitable
        tenacious
        invincible
        resilient
        radiant
        expressive
        trustworthy
        delightful
        positive
        invigorating
        resilient
        uplifting
        transformative
        authentic
        visionary
        innovative
        inspiring
        compassionate
        gentle
        wise
        harmonious
        caring
        affectionate
        courageous
        determined
        motivated
        honest
        patient
        joyful
        grateful
        kind
        generous
        understanding
        empathetic
        adventurous
        curious
        open-minded
        resilient
        flexible
        ambitious
        diligent
        organized
        disciplined
        skillful
        competent
        reliable
        efficient
        grateful
        humble
        appreciative
        innovative
        adventurous
        experienced
        insightful
        knowledgeable
        sensible
        polite
        professional
        supportive
        trustworthy
        brave
        charismatic
        collaborative
        courageous
        curious
        determined
        dynamic
        empathetic
        energetic
        enthusiastic
        expressive
        flexible
        fun-loving
        genuine
        gracious
        inquisitive
        intuitive
        joyful
        kind-hearted
        loving
        loyal
        nurturing
        optimistic
        passionate
        peaceful
        persistent
        playful
        positive
        resilient
        selfless
        spiritual
        talented
        thoughtful
        warm-hearted
        wise
        wonderful
        zealous
        magnetic
        artistic
        considerate
        dependable
        imaginative
        sociable
        ambitious
        attentive
        faithful
        inspiring
        reliable
        tenacious
        attentive
        compassionate
        diligent
        joyful
        supportive
        trustworthy
        wise
        unique
        inquisitive
        conscientious
        authentic
        positive
        optimistic
        caring
      ]
    end

    def nouns
      %w[
        waterfall river breeze moon rain wind sea morning
        snow lake sunset pine shadow leaf dawn glitter forest
        hill cloud meadow sun glade bird brook butterfly
        bush dew dust field fire flower firefly feather grass
        haze mountain night pond darkness snowflake silence
        sound sky shape surf thunder violet water wildflower
        wave water resonance sun log dream cherry tree fog
        frost voice paper frog smoke star
        koala vegemite acai jungle beach desert chocolate deer
        tiramisu island honey smoothie valley ocean earth
        plains camel coffee tea cookies soup dandelion sprinkles
        snail lullaby platypus painting wallaby flamingo owl
        otter fox pancake biscuit
        love
        smile
        laughter
        harmony
        rainbow
        music
        joy
        hope
        kindness
        friendship
        bliss
        happiness
        tranquility
        serenity
        beauty
        serenade
        whisper
        inspiration
        brilliance
        radiance
        marvel
        wonder
        elation
        delight
        serendipity
        magic
        enchantment
        treasure
        dreamer
        imagination
        enthusiasm
        passion
        success
        victory
        achievement
        creativity
        innovation
        transformation
        adventure
        exploration
        discovery
        enlightenment
        courage
        freedom
        empowerment
        wisdom
        knowledge
        enlightenment
        resilience
        tenacity
        determination
        faith
        inspiration
        serendipity
        miracle
        grace
        blessing
        kindred
        spirit
        compassion
        generosity
        gratitude
        abundance
        prosperity
        harmony
        unity
        balance
        renewal
        healing
        tranquility
        peace
        calm
        stillness
        wholeness
        contentment
        patience
        understanding
        serenity
        forgiveness
        resilience
        inspiration
        motivation
        joyfulness
        celebration
        excitement
        thrill
        wonderment
        ecstasy
        satisfaction
        fulfillment
        prosperity
        gratefulness
        optimism
        positivity
        refreshment
        revitalization
        energy
        rejuvenation
        vibrance
        vitality
        adventure
        exploration
        discovery
        wonder
        curiosity
        ascension
        awakening
        nirvana
        enlightenment
        tranquility
        eternity
        infinity
        infinity
        clarity
        reflection
        radiance
        blooming
        blossoming
        flourishing
        renewal
        rebirth
        purity
        impression
        progress
        growth
        achievement
        success
        fulfillment
        honesty
        integrity
        perseverance
        endurance
        resilience
        support
        encouragement
        nourishment
        inspiration
        motivation
        collaboration
        empathy
        kindness
        wisdom
        connectivity
        unity
        abundance
        goodness
        benevolence
        transformation
        miracle
        imagination
        creativity
        vision
        innovation
        brilliance
        mindfulness
        reverie
        amusement
        sensation
        warmth
        serenade
        whisper
        wonderment
        melody
        harmony
        honk
        buzz
        giggle
        pop
        sparkle
        radiance
        enchantment
        majestic
        embrace
        petal
        playfulness
        furry
        friend
        cookie
        sweetness
        symphony
        melody
        inspiration
        muse
        blossom
        joyride
        zest
        regeneration
        adventure
        embrace
        savor
        yearning
        meander
        wanderlust
        magic
        extravaganza
        jubilee
        feast
        feast
        legacy
        oasis
        haven
        enclave
        retreat
        exploration
        delicacy
        whimsey
        pizzazz
        lavishness
        marvel
        presence
        delight
        wonder
        essence
        restoration
        sanctuary
        charisma
        jubilation
        inspiration
        nirvana
        gift
        luminary
        infusion
        blessing
        betwixt
        betwixt
        splendor
        rhapsody
        whirl
        entrancement
        accolade
        euphoria
        venture
        utopia
        supernova
        soaring
        synergy
        triumph
        jubilee
        revelation
        delight
        miracle
        exhilaration
        triumph
        phenomenon
        rhapsody
        paradigm
        elevation
        thrive
        jubilation
        enchantment
        vibrancy
        zing
        clarity
        renaissance
        flourish
        pinnacle
        opulence
        vivacity
        momentum
        upliftment
        ecstasy
        rapture
        savor
        reverence
        luxuriance
        elixir
        bliss
        transcendence
        panache
        whiz
        cachet
        immersion
        illumination
        relish
        indulgence
        cascade
        enrichment
        extraordinaire
        supremacy
        epiphany
        sumptuousness
        zeal
        perfection
        fulfillment
        empowerment
        epitome
        brilliance
        marvel
        captivation
        reverie
        elation
        lushness
        quintessence
        eloquence
        aptitude
        talent
        splendor
        inspire
        legacy
        hearth
        exultation
        delicacy
      ]
    end
  end
end
